var data = [
    {
        title: "題目【百而千，千而萬】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "誠實",
        btn2_content: "忠孝",
        btn3_content: "愛心",
        correct_answer: "btn-1",
        hint: "謎面為三字經句，百乘十乃成千，千乘十乃成萬。",
        propaganda: "臺北市政府政風處製作「廉潔寶寶聯盟-勇敢吹哨篇」幼兒廉潔教材電子書，與臺北市政府教育局和臺北市國民教育輔導團幼兒教育輔導小組合作將「誠實、勇敢吹哨、不貪心、互相幫助」等核心價值，延伸教案及AR闖關遊戲，以多元方式提供親師共讀共學。",
        video_information: " ● 「廉潔寶寶聯盟_看到怪怪的請舉手（勇敢吹哨篇）幼兒廉潔教材」電子書",
        href: "https://www-ws.gov.taipei/001/Upload/377/ebook/ebook_2033450/index.html?ccms_cs=1",
        moudle_teach_video_a: `<img src="./img/moudle/hint-1.jpg" alt="" class="moudle-teach-video ">`
    },
    {
        title: "題目【三方鼎立，道本在心】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "廉潔",
        btn2_content: "誠信",
        btn3_content: "品德",
        correct_answer: "btn-3",
        hint: "三方（口字為方形）鼎立；《周禮·地官》：「在心為德，施之為行。」",
        propaganda: "為使廉潔教育向下扎根，臺北市政府推動品德教育實施計畫，臺北市政府政風處與教育局製作一系列廉潔教育教材，於臺北酷課雲架設廉潔教育專區，建構由小而大的廉潔教育網絡，培養學童誠信反貪觀念。",
        video_information: " ●  臺北市政風處-廉潔教育專區",
        href: "https://sites.google.com/view/interity-edu/%E9%A6%96%E9%A0%81",
        moudle_teach_video_a: ``
    },
    {
        title: "題目【春蠶吐絲，死而後已】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "誠信",
        btn2_content: "公正",
        btn3_content: "透明",
        correct_answer: "btn-2",
        hint: "謎面出自《李商隱 無題》：「春蠶到死絲方盡」，絲方盡表示「無絲」，諧音「無私」。",
        propaganda: "臺北市政府政風處與臺北市政府教育局、臺北市國民教育輔導團幼兒教育輔導小組合作製作「廉潔寶寶聯盟-誠信最棒篇」幼兒廉潔教材電子書，將「公平公正、利益衝突迴避、誠實信用、細心觀察、理直氣和」等核心價值，延伸教案5則，供教保服務人員、家長與幼兒共讀，使廉潔教育向下紮根。",
        video_information: "  ●  幼兒廉潔教育教材-廉潔寶寶聯盟",
        href: "http://www.abc.digimagic.com.tw/LJBB_ebook/index.html",
        moudle_teach_video_a: ``
    },
    {
        title: "題目【是謂是，非謂非】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "正義",
        btn2_content: "公平",
        btn3_content: "正直",
        correct_answer: "btn-3",
        hint: "謎面出自《荀子．修身》：「是謂是，非謂非，曰直。」",
        propaganda: "臺北市政府政風處製作廉潔布袋戲影片，將「廉潔自持、正直誠信」等核心價值，結合傳統布袋戲，以競爭掌門人之故事，讓觀眾在身歷其境的布袋戲武俠世界感受其中所蘊含的誠信意涵，理解並認同「拒絕賄賂、勇於揭弊」的重要性。",
        video_information: " ●  廉政布袋戲_戲說清微「掌門傳廉潔」",
        href: "https://www.youtube.com/watch?v=aoAc8BEGUnc",
        moudle_teach_video_a: `<iframe width="90%" height="90%" src="https://www.youtube.com/embed/aoAc8BEGUnc?controls=0" title="廉潔掌中戲「黑冠現形記」（中英字幕）" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
    },
    {
        title: "題目【不失方圓】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "守規矩",
        btn2_content: "守秩序",
        btn3_content: "守信用",
        correct_answer: "btn-1",
        hint: "謎面出自《孟子》的《離婁章句上》：「不以規矩，不能成方圓。」",
        propaganda: "臺北市政府政風處製作「廉潔寶寶聯盟-誠信最棒篇」動畫，以「公平比賽守規矩、誠實信用最安心」的核心價值，藉由生動活潑的動畫，傳達廉潔價值理念，自幼兒階段起即培養廉潔自持意識。",
        video_information: " ●  【廉潔寶寶聯盟 誠信最棒篇】廉潔寶寶們要參加跳舞比賽了！咦？好像有怪怪的事情發生了！為了守護比賽，廉潔寶寶聯盟再次出動！",
        href: "https://www.youtube.com/watch?v=JBBcBdyTFOs",
        moudle_teach_video_a: `<iframe width="90%" height="90%" src="https://www.youtube.com/embed/JBBcBdyTFOs" title="廉潔寶寶聯盟 誠信最棒篇" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
    },
    {
        title: "題目【龐涓改口為王出頭信平君頗不願出戰】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "守信",
        btn2_content: "清廉",
        btn3_content: "公平",
        correct_answer: "btn-2",
        hint: "龐涓為戰國時期軍事家，為魏惠王重用。廉頗為戰國時期名將，封信平君，傳長平之戰時，廉頗初戰不利後選擇守勢，不願出戰。（謎用增損法：涓字改口，替換成出頭王，為「清」字）",
        propaganda: "臺北市政府政風處與臺北市平等國小「巧宛然掌中劇團」合作，製作「黑冠現形記」影片，將廉潔觀念融入新冠肺炎時事，藉由欽差調查弊案，以詼諧、逗趣的方式傳達「清廉、守法」的概念。",
        video_information: "  ●  廉潔掌中戲「黑冠現形記」（中英字幕）",
        href: "https://www.youtube.com/watch?v=mvOQxetq1Oc",
        moudle_teach_video_a: `<iframe width="90%" height="90%" src="https://www.youtube.com/embed/mvOQxetq1Oc" title="廉潔掌中戲「黑冠現形記」（中英字幕）" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
    },
    {
        title: "題目【簾幕竹翦，熊火風偃】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "廉能",
        btn2_content: "廉潔",
        btn3_content: "賢能",
        correct_answer: "btn-1",
        hint: "謎用增損法：「簾」幕之竹翦除，「熊」熊火順風止息。",
        propaganda: "臺北市政府每年辦理選拔及表揚本府「廉能楷模」，藉由獲獎同仁的楷模示範，鼓勵同仁清廉自持， 提升本府廉能風氣。",
        video_information: "●  臺北市政風處-全球資訊網_廉能楷模",
        href: "https://doge.gov.taipei/News.aspx?n=5BCE1159E0DEF90D&sms=E9178972D5F0F1FB",
        moudle_teach_video_a: ``
    },
    {
        title: "題目【身直不怕斜啟窗莫愁黑】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "嚴守規矩",
        btn2_content: "行政透明",
        btn3_content: "高風亮節",
        correct_answer: "btn-2",
        hint: "身直就能行得正，門窗打開光線透進屋內就會明亮。",
        propaganda: "臺北市政府政風處編撰「第八屆廉能透明獎專刊」，介紹臺北市政府各機關推動透明化措施或系統之內容、建置過程及民眾使用情形，期望可供各單位在日後創設透明化措施或系統時之方向與指引參考，將「廉能透明」的效益擴散。",
        video_information: "  ●  臺北市政府第8界「廉能透明獎」專刊-電子書",
        href: "https://www-ws.gov.taipei/001/Upload/377/ebook/ebook_2087525/index.html",
        moudle_teach_video_a: `<img src="./img/moudle/hint-2.jpg" alt="" class="moudle-teach-video">`
    },
    {
        title: "題目【撥得雲開見白日】",
        subtitle: "猜猜看，謎底是以下哪一個選項呢?",
        btn1_content: "天行者",
        btn2_content: "影武者",
        btn3_content: "揭弊者",
        correct_answer: "btn-3",
        hint: "謎面改李白《登金陵鳳凰臺》：「總為浮雲能蔽日，長安不見使人愁。」",
        propaganda: "臺北市政府政風處製作廉潔布袋戲影片，將「廉潔自持、正直誠信」等核心價值，結合傳統布袋戲，以競爭掌門人之故事，讓觀眾在身歷其境的布袋戲武俠世界感受其中所蘊含的誠信意涵，理解並認同「拒絕賄賂、勇於揭弊」的重要性。此外，臺北市政府為維護揭弊者之權益，訂定「 臺北市政府揭弊者保護作業原則」。",
        video_information: "●  廉政布袋戲_戲說清微_掌門傳廉潔",
        href: "https://www.youtube.com/watch?v=aoAc8BEGUnc",
        moudle_teach_video_a: `<iframe width="90%" height="90%" src="https://www.youtube.com/embed/liXgOFdkKCM" title="廉潔掌中戲「黑冠現形記」（中英字幕）" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
    },
];